drop extension if exists "pg_net";


  create table "public"."climb_images" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "climb_id" bigint,
    "url" text
      );


alter table "public"."climb_images" enable row level security;


  create table "public"."climb_videos" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "climb_id" bigint,
    "user_id" uuid,
    "url" text
      );


alter table "public"."climb_videos" enable row level security;


  create table "public"."climbs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "grade" text,
    "city" text,
    "area" text,
    "subArea" text,
    "slug" text generated always as (lower(regexp_replace(name, '[^a-zA-Z0-9]+'::text, '-'::text, 'g'::text))) stored,
    "type" text
      );


alter table "public"."climbs" enable row level security;


  create table "public"."favorites" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "climb_id" bigint,
    "user_id" uuid
      );


alter table "public"."favorites" enable row level security;


  create table "public"."notes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "climb_id" bigint,
    "user_id" uuid,
    "note" text
      );


alter table "public"."notes" enable row level security;


  create table "public"."post_images" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "url" text,
    "post_id" bigint
      );


alter table "public"."post_images" enable row level security;


  create table "public"."post_videos" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "post_id" bigint,
    "url" text
      );


alter table "public"."post_videos" enable row level security;


  create table "public"."posts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text,
    "content" text
      );


alter table "public"."posts" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "username" text,
    "role" text default 'user'::text,
    "avatar_url" text,
    "created_at" timestamp without time zone default now(),
    "email" text
      );


alter table "public"."profiles" enable row level security;


  create table "public"."sends" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "climb_id" bigint
      );


alter table "public"."sends" enable row level security;

CREATE UNIQUE INDEX "Posts_pkey" ON public.posts USING btree (id);

CREATE UNIQUE INDEX climb_images_pkey ON public.climb_images USING btree (id);

CREATE UNIQUE INDEX climb_videos_pkey ON public.climb_videos USING btree (id);

CREATE UNIQUE INDEX climbs_pkey ON public.climbs USING btree (id);

CREATE UNIQUE INDEX climbs_unique_all ON public.climbs USING btree (name, type, grade, city, area, "subArea", slug);

CREATE UNIQUE INDEX favorites_pkey ON public.favorites USING btree (id);

CREATE UNIQUE INDEX notes_pkey ON public.notes USING btree (id);

CREATE UNIQUE INDEX "postImages_pkey" ON public.post_images USING btree (id);

CREATE UNIQUE INDEX post_videos_pkey ON public.post_videos USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_username_key ON public.profiles USING btree (username);

CREATE UNIQUE INDEX sends_pkey ON public.sends USING btree (id);

alter table "public"."climb_images" add constraint "climb_images_pkey" PRIMARY KEY using index "climb_images_pkey";

alter table "public"."climb_videos" add constraint "climb_videos_pkey" PRIMARY KEY using index "climb_videos_pkey";

alter table "public"."climbs" add constraint "climbs_pkey" PRIMARY KEY using index "climbs_pkey";

alter table "public"."favorites" add constraint "favorites_pkey" PRIMARY KEY using index "favorites_pkey";

alter table "public"."notes" add constraint "notes_pkey" PRIMARY KEY using index "notes_pkey";

alter table "public"."post_images" add constraint "postImages_pkey" PRIMARY KEY using index "postImages_pkey";

alter table "public"."post_videos" add constraint "post_videos_pkey" PRIMARY KEY using index "post_videos_pkey";

alter table "public"."posts" add constraint "Posts_pkey" PRIMARY KEY using index "Posts_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."sends" add constraint "sends_pkey" PRIMARY KEY using index "sends_pkey";

alter table "public"."climb_images" add constraint "climb_images_climb_id_fkey" FOREIGN KEY (climb_id) REFERENCES public.climbs(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."climb_images" validate constraint "climb_images_climb_id_fkey";

alter table "public"."climb_videos" add constraint "climb_videos_climb_id_fkey" FOREIGN KEY (climb_id) REFERENCES public.climbs(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."climb_videos" validate constraint "climb_videos_climb_id_fkey";

alter table "public"."climb_videos" add constraint "climb_videos_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."climb_videos" validate constraint "climb_videos_user_id_fkey";

alter table "public"."climbs" add constraint "climbs_unique_all" UNIQUE using index "climbs_unique_all";

alter table "public"."favorites" add constraint "favorites_climb_id_fkey" FOREIGN KEY (climb_id) REFERENCES public.climbs(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."favorites" validate constraint "favorites_climb_id_fkey";

alter table "public"."favorites" add constraint "favorites_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."favorites" validate constraint "favorites_user_id_fkey";

alter table "public"."notes" add constraint "notes_climbId_fkey" FOREIGN KEY (climb_id) REFERENCES public.climbs(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."notes" validate constraint "notes_climbId_fkey";

alter table "public"."notes" add constraint "notes_userId_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."notes" validate constraint "notes_userId_fkey";

alter table "public"."post_images" add constraint "postImages_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.posts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."post_images" validate constraint "postImages_post_id_fkey";

alter table "public"."post_videos" add constraint "post_videos_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.posts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."post_videos" validate constraint "post_videos_post_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_username_key" UNIQUE using index "profiles_username_key";

alter table "public"."sends" add constraint "sends_climb_id_fkey" FOREIGN KEY (climb_id) REFERENCES public.climbs(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."sends" validate constraint "sends_climb_id_fkey";

alter table "public"."sends" add constraint "sends_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."sends" validate constraint "sends_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles (id, username, avatar_url)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'user_name',
      new.raw_user_meta_data ->> 'full_name',
      split_part(new.email, '@', 1)
    ),
    new.raw_user_meta_data ->> 'avatar_url'
  );
  return new;
end;
$function$
;

grant delete on table "public"."climb_images" to "anon";

grant insert on table "public"."climb_images" to "anon";

grant references on table "public"."climb_images" to "anon";

grant select on table "public"."climb_images" to "anon";

grant trigger on table "public"."climb_images" to "anon";

grant truncate on table "public"."climb_images" to "anon";

grant update on table "public"."climb_images" to "anon";

grant delete on table "public"."climb_images" to "authenticated";

grant insert on table "public"."climb_images" to "authenticated";

grant references on table "public"."climb_images" to "authenticated";

grant select on table "public"."climb_images" to "authenticated";

grant trigger on table "public"."climb_images" to "authenticated";

grant truncate on table "public"."climb_images" to "authenticated";

grant update on table "public"."climb_images" to "authenticated";

grant delete on table "public"."climb_images" to "service_role";

grant insert on table "public"."climb_images" to "service_role";

grant references on table "public"."climb_images" to "service_role";

grant select on table "public"."climb_images" to "service_role";

grant trigger on table "public"."climb_images" to "service_role";

grant truncate on table "public"."climb_images" to "service_role";

grant update on table "public"."climb_images" to "service_role";

grant delete on table "public"."climb_videos" to "anon";

grant insert on table "public"."climb_videos" to "anon";

grant references on table "public"."climb_videos" to "anon";

grant select on table "public"."climb_videos" to "anon";

grant trigger on table "public"."climb_videos" to "anon";

grant truncate on table "public"."climb_videos" to "anon";

grant update on table "public"."climb_videos" to "anon";

grant delete on table "public"."climb_videos" to "authenticated";

grant insert on table "public"."climb_videos" to "authenticated";

grant references on table "public"."climb_videos" to "authenticated";

grant select on table "public"."climb_videos" to "authenticated";

grant trigger on table "public"."climb_videos" to "authenticated";

grant truncate on table "public"."climb_videos" to "authenticated";

grant update on table "public"."climb_videos" to "authenticated";

grant delete on table "public"."climb_videos" to "service_role";

grant insert on table "public"."climb_videos" to "service_role";

grant references on table "public"."climb_videos" to "service_role";

grant select on table "public"."climb_videos" to "service_role";

grant trigger on table "public"."climb_videos" to "service_role";

grant truncate on table "public"."climb_videos" to "service_role";

grant update on table "public"."climb_videos" to "service_role";

grant delete on table "public"."climbs" to "anon";

grant insert on table "public"."climbs" to "anon";

grant references on table "public"."climbs" to "anon";

grant select on table "public"."climbs" to "anon";

grant trigger on table "public"."climbs" to "anon";

grant truncate on table "public"."climbs" to "anon";

grant update on table "public"."climbs" to "anon";

grant delete on table "public"."climbs" to "authenticated";

grant insert on table "public"."climbs" to "authenticated";

grant references on table "public"."climbs" to "authenticated";

grant select on table "public"."climbs" to "authenticated";

grant trigger on table "public"."climbs" to "authenticated";

grant truncate on table "public"."climbs" to "authenticated";

grant update on table "public"."climbs" to "authenticated";

grant delete on table "public"."climbs" to "service_role";

grant insert on table "public"."climbs" to "service_role";

grant references on table "public"."climbs" to "service_role";

grant select on table "public"."climbs" to "service_role";

grant trigger on table "public"."climbs" to "service_role";

grant truncate on table "public"."climbs" to "service_role";

grant update on table "public"."climbs" to "service_role";

grant delete on table "public"."favorites" to "anon";

grant insert on table "public"."favorites" to "anon";

grant references on table "public"."favorites" to "anon";

grant select on table "public"."favorites" to "anon";

grant trigger on table "public"."favorites" to "anon";

grant truncate on table "public"."favorites" to "anon";

grant update on table "public"."favorites" to "anon";

grant delete on table "public"."favorites" to "authenticated";

grant insert on table "public"."favorites" to "authenticated";

grant references on table "public"."favorites" to "authenticated";

grant select on table "public"."favorites" to "authenticated";

grant trigger on table "public"."favorites" to "authenticated";

grant truncate on table "public"."favorites" to "authenticated";

grant update on table "public"."favorites" to "authenticated";

grant delete on table "public"."favorites" to "service_role";

grant insert on table "public"."favorites" to "service_role";

grant references on table "public"."favorites" to "service_role";

grant select on table "public"."favorites" to "service_role";

grant trigger on table "public"."favorites" to "service_role";

grant truncate on table "public"."favorites" to "service_role";

grant update on table "public"."favorites" to "service_role";

grant delete on table "public"."notes" to "anon";

grant insert on table "public"."notes" to "anon";

grant references on table "public"."notes" to "anon";

grant select on table "public"."notes" to "anon";

grant trigger on table "public"."notes" to "anon";

grant truncate on table "public"."notes" to "anon";

grant update on table "public"."notes" to "anon";

grant delete on table "public"."notes" to "authenticated";

grant insert on table "public"."notes" to "authenticated";

grant references on table "public"."notes" to "authenticated";

grant select on table "public"."notes" to "authenticated";

grant trigger on table "public"."notes" to "authenticated";

grant truncate on table "public"."notes" to "authenticated";

grant update on table "public"."notes" to "authenticated";

grant delete on table "public"."notes" to "service_role";

grant insert on table "public"."notes" to "service_role";

grant references on table "public"."notes" to "service_role";

grant select on table "public"."notes" to "service_role";

grant trigger on table "public"."notes" to "service_role";

grant truncate on table "public"."notes" to "service_role";

grant update on table "public"."notes" to "service_role";

grant delete on table "public"."post_images" to "anon";

grant insert on table "public"."post_images" to "anon";

grant references on table "public"."post_images" to "anon";

grant select on table "public"."post_images" to "anon";

grant trigger on table "public"."post_images" to "anon";

grant truncate on table "public"."post_images" to "anon";

grant update on table "public"."post_images" to "anon";

grant delete on table "public"."post_images" to "authenticated";

grant insert on table "public"."post_images" to "authenticated";

grant references on table "public"."post_images" to "authenticated";

grant select on table "public"."post_images" to "authenticated";

grant trigger on table "public"."post_images" to "authenticated";

grant truncate on table "public"."post_images" to "authenticated";

grant update on table "public"."post_images" to "authenticated";

grant delete on table "public"."post_images" to "service_role";

grant insert on table "public"."post_images" to "service_role";

grant references on table "public"."post_images" to "service_role";

grant select on table "public"."post_images" to "service_role";

grant trigger on table "public"."post_images" to "service_role";

grant truncate on table "public"."post_images" to "service_role";

grant update on table "public"."post_images" to "service_role";

grant delete on table "public"."post_videos" to "anon";

grant insert on table "public"."post_videos" to "anon";

grant references on table "public"."post_videos" to "anon";

grant select on table "public"."post_videos" to "anon";

grant trigger on table "public"."post_videos" to "anon";

grant truncate on table "public"."post_videos" to "anon";

grant update on table "public"."post_videos" to "anon";

grant delete on table "public"."post_videos" to "authenticated";

grant insert on table "public"."post_videos" to "authenticated";

grant references on table "public"."post_videos" to "authenticated";

grant select on table "public"."post_videos" to "authenticated";

grant trigger on table "public"."post_videos" to "authenticated";

grant truncate on table "public"."post_videos" to "authenticated";

grant update on table "public"."post_videos" to "authenticated";

grant delete on table "public"."post_videos" to "service_role";

grant insert on table "public"."post_videos" to "service_role";

grant references on table "public"."post_videos" to "service_role";

grant select on table "public"."post_videos" to "service_role";

grant trigger on table "public"."post_videos" to "service_role";

grant truncate on table "public"."post_videos" to "service_role";

grant update on table "public"."post_videos" to "service_role";

grant delete on table "public"."posts" to "anon";

grant insert on table "public"."posts" to "anon";

grant references on table "public"."posts" to "anon";

grant select on table "public"."posts" to "anon";

grant trigger on table "public"."posts" to "anon";

grant truncate on table "public"."posts" to "anon";

grant update on table "public"."posts" to "anon";

grant delete on table "public"."posts" to "authenticated";

grant insert on table "public"."posts" to "authenticated";

grant references on table "public"."posts" to "authenticated";

grant select on table "public"."posts" to "authenticated";

grant trigger on table "public"."posts" to "authenticated";

grant truncate on table "public"."posts" to "authenticated";

grant update on table "public"."posts" to "authenticated";

grant delete on table "public"."posts" to "service_role";

grant insert on table "public"."posts" to "service_role";

grant references on table "public"."posts" to "service_role";

grant select on table "public"."posts" to "service_role";

grant trigger on table "public"."posts" to "service_role";

grant truncate on table "public"."posts" to "service_role";

grant update on table "public"."posts" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."sends" to "anon";

grant insert on table "public"."sends" to "anon";

grant references on table "public"."sends" to "anon";

grant select on table "public"."sends" to "anon";

grant trigger on table "public"."sends" to "anon";

grant truncate on table "public"."sends" to "anon";

grant update on table "public"."sends" to "anon";

grant delete on table "public"."sends" to "authenticated";

grant insert on table "public"."sends" to "authenticated";

grant references on table "public"."sends" to "authenticated";

grant select on table "public"."sends" to "authenticated";

grant trigger on table "public"."sends" to "authenticated";

grant truncate on table "public"."sends" to "authenticated";

grant update on table "public"."sends" to "authenticated";

grant delete on table "public"."sends" to "service_role";

grant insert on table "public"."sends" to "service_role";

grant references on table "public"."sends" to "service_role";

grant select on table "public"."sends" to "service_role";

grant trigger on table "public"."sends" to "service_role";

grant truncate on table "public"."sends" to "service_role";

grant update on table "public"."sends" to "service_role";


  create policy "Enable all access for all users"
  on "public"."climb_images"
  as permissive
  for all
  to public
using (true);



  create policy "Enable all access for all users"
  on "public"."climb_videos"
  as permissive
  for all
  to public
using (true);



  create policy "Enable all access for all users"
  on "public"."climbs"
  as permissive
  for all
  to public
using (true);



  create policy "Enable all access for all users"
  on "public"."favorites"
  as permissive
  for all
  to public
using (true);



  create policy "Enable all access for all users"
  on "public"."notes"
  as permissive
  for all
  to public
using (true);



  create policy "Enable all access for all users"
  on "public"."post_images"
  as permissive
  for all
  to public
using (true);



  create policy "Enable all access for all users"
  on "public"."post_videos"
  as permissive
  for all
  to public
using (true);



  create policy "Enable all access for all users"
  on "public"."posts"
  as permissive
  for all
  to public
using (true);



  create policy "Public profiles are viewable"
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "Users can update own profile (except role)"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id))
with check (((auth.uid() = id) AND (role = ( SELECT profiles_1.role
   FROM public.profiles profiles_1
  WHERE (profiles_1.id = auth.uid())))));



  create policy "Users can update own profile"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id));



  create policy "Enable all access for all users"
  on "public"."sends"
  as permissive
  for all
  to public
using (true);


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "all users have access lxdu7s_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'postImages'::text));



  create policy "all users have access lxdu7s_1"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'postImages'::text));



  create policy "all users have access lxdu7s_2"
  on "storage"."objects"
  as permissive
  for update
  to public
using ((bucket_id = 'postImages'::text));



  create policy "all users have access lxdu7s_3"
  on "storage"."objects"
  as permissive
  for delete
  to public
using ((bucket_id = 'postImages'::text));



